#!/bin/bash

echo "--------------------------------------------------"
echo "All Files `ls`"
echo "--------------------------------------------------"
echo "All Files with Hidden Files `ls -a`"
echo "--------------------------------------------------"
echo "All Hidden Files `ls -ld .*`"
echo "--------------------------------------------------"
echo "Space occupied by Files `ls -l --block-size=kB`"
echo "--------------------------------------------------"
echo "All Directories `ls -d */`"
echo "--------------------------------------------------"
echo "Type of Files `ls`"
echo "--------------------------------------------------"
echo "Sorted Files `ls -cl`"
echo "--------------------------------------------------"
