/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2018-01-13 11:54:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.psl.entity.*;
import com.psl.dao.*;
import java.util.*;
import java.text.*;
import java.util.*;

public final class adminUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


//get UserName to verify 
String userName= (String) session.getAttribute("firstname");
String type=(String) session.getAttribute("usertype");
if(userName!=null && type.equalsIgnoreCase("administrator"))
{

//user is valid

}
else
{

//return here as user is invalid
response.sendRedirect("login.html");

}


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Reports - Room Booking Calendar</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/bootstrap-responsive.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"sweet-alert.css\">\r\n");
      out.write("<script src=\"js/sweet-alert.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.10.2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"//code.jquery.com/ui/1.11.2/jquery-ui.js\"></script>\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"jquery-1.11.1.js\"></script> -->\r\n");
      out.write("<link href=\"css/pages/reports.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/freezeHeader.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".CSSTableGenerator {\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tborder: 1px solid #000000;\r\n");
      out.write("\t-moz-border-radius-bottomleft: 0px;\r\n");
      out.write("\t-webkit-border-bottom-left-radius: 0px;\r\n");
      out.write("\tborder-bottom-left-radius: 0px;\r\n");
      out.write("\t-moz-border-radius-bottomright: 0px;\r\n");
      out.write("\t-webkit-border-bottom-right-radius: 0px;\r\n");
      out.write("\tborder-bottom-right-radius: 0px;\r\n");
      out.write("\t-moz-border-radius-topright: 0px;\r\n");
      out.write("\t-webkit-border-top-right-radius: 0px;\r\n");
      out.write("\tborder-top-right-radius: 0px;\r\n");
      out.write("\t-moz-border-radius-topleft: 0px;\r\n");
      out.write("\t-webkit-border-top-left-radius: 0px;\r\n");
      out.write("\tborder-top-left-radius: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".CSSTableGenerator table {\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("\tborder-spacing: 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".CSSTableGenerator tr:last-child td:last-child {\r\n");
      out.write("\t-moz-border-radius-bottomright: 0px;\r\n");
      out.write("\t-webkit-border-bottom-right-radius: 0px;\r\n");
      out.write("\tborder-bottom-right-radius: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".CSSTableGenerator table tr:first-child th:first-child {\r\n");
      out.write("\t-moz-border-radius-topleft: 0px;\r\n");
      out.write("\t-webkit-border-top-left-radius: 0px;\r\n");
      out.write("\tborder-top-left-radius: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".CSSTableGenerator table tr:first-child th:last-child {\r\n");
      out.write("\t-moz-border-radius-topright: 0px;\r\n");
      out.write("\t-webkit-border-top-right-radius: 0px;\r\n");
      out.write("\tborder-top-right-radius: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".CSSTableGenerator tr:last-child th:first-child {\r\n");
      out.write("\t-moz-border-radius-bottomleft: 0px;\r\n");
      out.write("\t-webkit-border-bottom-left-radius: 0px;\r\n");
      out.write("\tborder-bottom-left-radius: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".CSSTableGenerator tr:hover td {\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("/*  .CSSTableGenerator tr:nth-child(odd){ background-color:#ffaa56; }\r\n");
      out.write(".CSSTableGenerator tr:nth-child(even)    { background-color:#ffffff;\r\n");
      out.write("} */\r\n");
      out.write(".CSSTableGenerator td, th {\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tborder: 1px solid #000000;\r\n");
      out.write("\tborder-width: 0px 1px 1px 0px;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tpadding: 14px;\r\n");
      out.write("\tfont-size: 10px;\r\n");
      out.write("\tfont-family: Arial;\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("\tcolor: #000000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".CSSTableGenerator tr:last-child td {\r\n");
      out.write("\tborder-width: 0px 1px 0px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".CSSTableGenerator tr td:last-child {\r\n");
      out.write("\tborder-width: 0px 0px 1px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".CSSTableGenerator tr:last-child td:last-child {\r\n");
      out.write("\tborder-width: 0px 0px 0px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".CSSTableGenerator tr:first-child th {\r\n");
      out.write("\tbackground: -o-linear-gradient(bottom, #e3e3e3 5%, #e9e9e9 100%);\r\n");
      out.write("\tbackground: -webkit-gradient(linear, left top, left bottom, color-stop(0.05, #e3e3e3\r\n");
      out.write("\t\t), color-stop(1, #e9e9e9));\r\n");
      out.write("\tbackground: -moz-linear-gradient(center top, #e3e3e3 5%, #e9e9e9 100%);\r\n");
      out.write("\tfilter: progid:DXImageTransform.Microsoft.gradient(startColorstr=\"#e3e3e3\",\r\n");
      out.write("\t\tendColorstr=\"#e9e9e9\");\r\n");
      out.write("\tbackground: -o-linear-gradient(top, #e3e3e3, e9e9e9);\r\n");
      out.write("\tbackground-color: #e3e3e3;\r\n");
      out.write("\tborder: 0px solid #000000;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tborder-width: 0px 0px 1px 1px;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tfont-family: Arial;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".CSSTableGenerator tr:first-child th:first-child {\r\n");
      out.write("\tborder-width: 0px 0px 1px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".CSSTableGenerator tr:first-child th:last-child {\r\n");
      out.write("\tborder-width: 0px 0px 1px 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".c0 {\r\n");
      out.write("\tbackground-color: green;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".c1 {\r\n");
      out.write("\tbackground-color: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".c2 {\r\n");
      out.write("\tbackground-color: orange;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t  \t\t\t\t\t$(function() {\r\n");
      out.write("\t  \t\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\t//$(\".CSSTableGenerator td\").tooltip();   \r\n");
      out.write("\t  \t\t\t\t\t\t$(\"#popover\").popover({ trigger: \"hover\" });\r\n");
      out.write("\t  \t\t\t\t\t\t$(\"#statusTable TD\").click(function(){\r\n");
      out.write("\t  \t\t\t\t\t\t\t//alert(\"td selected\");\r\n");
      out.write("\t  \t\t\t\t\t\t\t$(this).css(\"background-color\",\"red\");\t\r\n");
      out.write("\t  \t\t\t\t\t\t});\r\n");
      out.write("\t  \t\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t    \r\n");
      out.write("\t  \t\t\t\t\t\t$(\"#datepicker1,#datepicker2\").datepicker(\r\n");
      out.write("\t  \t\t\t\t\t\t{\r\n");
      out.write("\t  \t\t\t\t\t\t\tdateFormat:'yy-m-dd'\r\n");
      out.write("\t  \t\t\t\t\t\t}\t\t\r\n");
      out.write("\t  \t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\t);\r\n");
      out.write("\t  \t\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\t$(\"#book\").click(function(){\r\n");
      out.write("\t  \t\t\t\t\t\t\t$.get(\"book1.jsp\");\r\n");
      out.write("\t  \t\t\t\t\t\t});\r\n");
      out.write("\t  \t\t\t\t\t\t$(\"#view\").click(function(){\r\n");
      out.write("\t  \t\t\t\t\t\t\t//alert('hi');\r\n");
      out.write("\t  \t\t\t\t\t\t\t$.get(\"viewbooking.jsp\");\r\n");
      out.write("\t  \t\t\t\t\t\t});\r\n");
      out.write(" \t  \t\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\tgetLocation();\r\n");
      out.write("\t  \t\t\t\t\t  });\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\tfunction getLocation()\r\n");
      out.write("\t  \t\t\t\t\t{\r\n");
      out.write("\t  \t\t\t\t\t\t//alert(\"In get Location\");\r\n");
      out.write("\t  \t\t\t\t\t\t$.ajax(\r\n");
      out.write("\t  \t\t\t\t\t\t{\r\n");
      out.write("\t  \t\t\t\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t  \t\t\t\t\t\t\t\t\turl:\"GetLocation\",\r\n");
      out.write("\t  \t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\t\t\t\tdataType:\"JSON\" ,\r\n");
      out.write("\t  \t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t  \t\t\t\t\t\t\t\t\tsuccess:function(data)\r\n");
      out.write("\t  \t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t  \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\t\t\t\t\tfor(\r\n");
      out.write("\t  \t\t\t\t\t\t\t\t\t\t\t\tvar i=0;i<data.length;i++)\r\n");
      out.write("\t  \t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t  \t\t\t\t\t\t\t\t\t\t\t//alert(data[i]);\r\n");
      out.write("\t  \t\t\t\t\t\t\t\t\t\t\t$(\"#locationSelect\").append(\"<option>\"+data[i]+\"</option>\");\r\n");
      out.write("\t  \t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t  \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\terror:function(data,status,error)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\talert(data[1]);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\talert(\"Error occured in ajax\"+error+\":\"+status);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t  \t\t\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\t});\r\n");
      out.write("\t  \t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t  \t\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t}\r\n");
      out.write("\t  \t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t   \r\n");
      out.write("\t  \t\t\t\t\t \r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"navbar navbar-fixed-top\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"navbar-inner\">\r\n");
      out.write("\t\t\t<div class=\"left\">\r\n");
      out.write("\t\t\t\t<img alt=\"\" src=\"PSLLogo.jpg\" width=\"70px\" height=\"70px\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<a class=\"btn btn-navbar\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\".nav-collapse\"> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</a> <a class=\"brand\" href=\"adminUser.jsp\"> Room Booking Calendar\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"nav-collapse\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav pull-right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\"><a href=\"#\"><i class=\"icon-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(session.getAttribute("firstname"));
      out.write(" </a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"signout.jsp\"> <i class=\"icon-cog\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\tSign Out\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--/.nav-collapse -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /container -->\r\n");
      out.write("\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t<img alt=\"\" src=\"kc-logo-header (1).png\" width=\"70px\" height=\"70px\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /navbar-inner -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /navbar -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"subnavbar\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"subnavbar-inner\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"mainnav\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"adminUser.jsp\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-dashboard\"></i> <span>DashBoard</span>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"addroom.jsp\"> <i class=\"icon-credit-card\"></i>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<span>Add New Room</span>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"addUser.jsp\"> <i class=\"icon-user\"></i> <span>Add\r\n");
      out.write("\t\t\t\t\t\t\t\tUser</span>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"addlocation.jsp\"> <i class=\" icon-home\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Add Location</span>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /container -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /subnavbar-inner -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /subnavbar -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"main-inner\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"span12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-header\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <i class=\"icon-user\"></i> -->\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Location</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"locationSelect\">\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Start Date</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"datepicker1\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>End Date</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"datepicker2\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <input type=\"checkbox\" id=\"lab\" checked=\"checked\">\r\n");
      out.write("\t  \t\t\t\t\tLab<input type=\"checkbox\" id=\"softskill\" checked=\"checked\">\r\n");
      out.write("\t  \t\t\t\t\tSoftskill -->\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" id=\"go\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"button btn btn-primary btn-large\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <button id=\"go\">Go</button> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t  \t\t$(function() {\r\n");
      out.write("\t  \t\t\t\r\n");
      out.write("\t  \t\t\t\r\n");
      out.write("\t  \t\t\tif(");
      out.print(session.getAttribute("bookvalue"));
      out.write("==true)\r\n");
      out.write("\t\t  \t\t\t{sweetAlertInitialize();\r\n");
      out.write("\t\t  \t\t\t sweetAlert(\"Done...!\", \"Room booked Successfully!\");\r\n");
      out.write("\t\t  \t\t\t \t//alert(\"UserName already exists..!!Please enter another UserName\"); \r\n");
      out.write("\t\t  \t\t\t \t");

		  			session.setAttribute("bookvalue","false");
		  			 	
      out.write("\r\n");
      out.write("\t\t  \t\t/* \t \talert(\"firstname:\"+name);   */\r\n");
      out.write("\t\t  \t\t\t\r\n");
      out.write("\t\t  \t\t\t\r\n");
      out.write("\t\t  \t\t\t}\r\n");
      out.write("\t  \t\t\t\r\n");
      out.write("\t  \t\t\t\r\n");
      out.write("\t  \t\t\t\r\n");
      out.write("\t  \t\t\t\r\n");
      out.write("\t  \t\t\t\r\n");
      out.write("\t  \t\t\t\r\n");
      out.write("\t  \t\t\t\r\n");
      out.write("\t  \t\t\t//alert(\"Inside second ready\");\r\n");
      out.write("\t  \t\t\t$(\"#go\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t//alert(\"Go clicked\");\r\n");
      out.write("\t\t\t\t\t\tvar startDate=$(\"#datepicker1\").val();\r\n");
      out.write("\t\t\t\t\t\tvar endDate=$(\"#datepicker2\").val();;\r\n");
      out.write("\t\t\t\t\t\tvar roomType;\r\n");
      out.write("\t\t\t\t\t\tif ($('#lab').is(\":checked\") && $('#lab').is(\":checked\"))\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t  roomType=\"both\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\telse if ($('#lab').is(\":checked\") )\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t  roomType=\"lab\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\telse if ($('#softskill').is(\":checked\"))\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t roomType=\"softskill\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t roomType=\"both\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t//alert($(\"#locationSelect\").val());\r\n");
      out.write("\t\t\t\t\t\t\tvar loc = $(\"#locationSelect\").val();\r\n");
      out.write("\t\t\t\t\t\t\tvar  roomlist;\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t  \t\t\t $.ajax(\r\n");
      out.write("\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\turl:\"ajaxtable.jsp\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdatatype:\"json\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//data:{loc:$(\"#locationSelect\").val()},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata:{loc:loc,sDate:startDate,eDate:endDate,type:roomType},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsuccess:function(data)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//$('#tablediv#1234').html(data).freezeHeader({'height':'300px'});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$('#tablediv').html(data);\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t//$('#1234 tbody').css({\"width\":\"100%\",\"height\":\"400px\",\"overflow\":\"auto\", \"margin\":\"0 auto\" }); */\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\terror:function(data,status,error)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talert(data[1]);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talert(\"Error occured in ajax\"+error+\":\"+status);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t  \t\t\t \r\n");
      out.write("\t\t\t\t  \t\t\r\n");
      out.write("\t\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t  \t\t\t \r\n");
      out.write("\t\t\t\t  \t\t\t \r\n");
      out.write("\t\t\t\t  \t\t\t \r\n");
      out.write("\t\t\t\t  \t\t\t \r\n");
      out.write("\t\t\t\t  \t\t\t \r\n");
      out.write("\t\t\t\t  \t\t\t \r\n");
      out.write("\t\t\t\t  \t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t        \t\r\n");
      out.write("\t\t        }); \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\r\n");
      out.write("\t  \t\t});\r\n");
      out.write("\t  \t\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"info-box\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <div class=\"row-fluid stats-box\"  > -->\r\n");
      out.write("\t\t\t\t\t\t\t<!--  <div id=\"tbhead\" style=\"width:100%;height:250px;overflow:auto;margin:0 auto;\"></div> -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <div id=\"tablediv\" style=\"width:100%;height:250px;overflow:auto;margin:0 auto;\"></div> -->\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"tablediv\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 100%; height: 750px; margin: 0 auto; overflow: auto;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- </div>     -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><font color=\"Red\">*Please check room\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tavailability on DashBoard before proceeding to Book Room</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"50px\" height=\"5px\" class=\"c0\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Available</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"50px\" height=\"5px\" class=\"c2\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Partial</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"50px\" height=\"5px\" class=\"c1\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Fully Booked</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"widget-header\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"button btn btn-primary btn-large\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonClick=\"window.location='book1.jsp';\" id=\"book\">Book\r\n");
      out.write("\t\t\t\t\t\t\t\t\tRoom</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"recurrenceForm.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"button btn btn-primary btn-large\">Recurrence </a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"viewbooking.jsp\" target=\"_parent\"><button\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"button btn btn-primary btn-large\" id=\"view\">View\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tMy Bookings</button></a> <a href=\"viewbookingall.jsp\" target=\"_parent\"><button\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"button btn btn-primary btn-large\" id=\"view\">View\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tAll Bookings</button></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--  </div>\r\n");
      out.write("         </div>      \r\n");
      out.write("\t      \t -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /container -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /main-inner -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /main -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- <script src=\"js/jquery-1.7.2.min.js\"></script> -->\r\n");
      out.write("\t<script src=\"js/excanvas.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/chart.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("\t<script src=\"js/base.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
